// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBR.Data;

namespace SBR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190827020218_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SBR.Models.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Nombre");

                    b.Property<int?>("PropiedadId");

                    b.Property<string>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Caracteristicas");
                });

            modelBuilder.Entity("SBR.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("FechaFinal");

                    b.Property<DateTime>("FechaInicio");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SBR.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contacto");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SBR.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<int?>("CitaId");

                    b.Property<string>("ContactoPropietario");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Moneda");

                    b.Property<string>("NombrePropietario");

                    b.Property<double>("Precio");

                    b.Property<string>("Tipo");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("Propiedades");
                });

            modelBuilder.Entity("SBR.Models.Caracteristica", b =>
                {
                    b.HasOne("SBR.Models.Cliente")
                        .WithMany("Intereses")
                        .HasForeignKey("ClienteId");

                    b.HasOne("SBR.Models.Propiedad")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("PropiedadId");
                });

            modelBuilder.Entity("SBR.Models.Cita", b =>
                {
                    b.HasOne("SBR.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("SBR.Models.Propiedad", b =>
                {
                    b.HasOne("SBR.Models.Cita")
                        .WithMany("Propiedades")
                        .HasForeignKey("CitaId");
                });
#pragma warning restore 612, 618
        }
    }
}
