// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBR.Data;

namespace SBR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190809211008_ModelMigration2")]
    partial class ModelMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SBR.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Precio");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Propiedades");
                });
#pragma warning restore 612, 618
        }
    }
}
